name: AI Content Automation

# Schedule the workflow to run automatically
on:
  schedule:
    # Run at 2:25 AM Bangladesh Time (8:25 PM UTC) - TEST
    - cron: '25 20 * * *'
    # Alternative schedules (commented out):
    # - cron: '0 */6 * * *'   # Every 6 hours (4 times per day)
    # - cron: '0 9 * * *'     # Daily at 9 AM UTC
    # - cron: '0 9 * * 1,3,5' # Monday, Wednesday, Friday at 9 AM UTC
    # - cron: '0 9,15 * * *'  # Twice daily at 9 AM and 3 PM UTC
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
    
    - name: Run AI Content Generator
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: credentials.json
      run: |
        python cloud_main.py
    
    - name: Clean up credentials
      if: always()
      run: |
        rm -f credentials.json
    
    - name: Upload logs (if needed)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: error-logs
        path: |
          *.log
          *.txt
        retention-days: 7
